// Import necessary packages/modules
const svgCaptcha = require('svg-captcha');
const createShape = require('./shapes');
const getUserInput = require('./userInput');
const writeToFile = require('./fileWriter');

async function main() {
  //Get user input (getUserInput() function from UserInput.js)
  const userInput = await getUserInput();

  //Create shape based on user input (createShape(shapeType, shapeColor) function from shapes.js)
  const shape = createShape(answers.shapeType, answers.shapeColor)

  // Generating the SVG image by calling the svgCaptcha function with the text property of the answers object and saving it to a file
  // svgCaptcha(text, options)
    // .data is used to access the SVG image data generated by the svgCaptcha() function.
    //necessary because we need to pass the SVG image data to the response object of an HTTP server, which is used to send the image to the client's web browser
  const svg = svgCaptcha(answers.text, {
    size: 4,
    noise: 1,
    color: true,
    background: userInput.shapeColor,
    width: 300,
    height: 200,
    fontSize: 80,
    charPreset: 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789',
    ignoreChars: '0o1i',
    }).data;

  // Set the text color
  const textColor = answers.textColor;

  // Add text to the SVG image
  const svgWithText = shape.addText(svg, answers.txt, textColor);


}


  // then() =  built in method of Promise object used to handle fullfillment/rejection of Promise.
  .then((answers) => {
 

  
  });
