// Import necessary packages
const inquirer = require('inquirer');
const svgCaptcha = require('svg-captcha');
const fs = require('fs');


  // then() =  built in method of Promise object used to handle fullfillment/rejection of Promise.
  .then((answers) => {
    // Generating the SVG image by calling the svgCaptcha function with the text property of the answers object and saving it to a file
    // svgCaptcha(text, options)
    // .data is used to access the SVG image data generated by the svgCaptcha() function.
        //necessary because we need to pass the SVG image data to the response object of an HTTP server, which is used to send the image to the client's web browser
        //svg variable will be passed to the response object (later in the code)
    const svg = svgCaptcha(answers.text, {
        size: 4,
        noise: 1,
        color: true,
        background: answers.shapeColor,
        width: 300,
        height: 200,
        fontSize: 80,
        charPreset: 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789',
        ignoreChars: '0o1i',
      }).data;

  
  });
