const svgCaptcha = require('svg-captcha');
const getUserInput = require('./userInput');
const shapes = require('./shapes');

// Define function for creating a logo
async function createLogo() {
    try {
      // Get user input
      const answers = await getUserInput();
  
      // Create shape based on user input
      const shape = shapes.createShape(answers.shapeType, answers.shapeColor);
  
      // Generating the SVG image by calling the svgCaptcha function with the text property of the answers object and saving it to a file
      // svgCaptcha(text, options)
      // .data is used to access the SVG image data generated by the svgCaptcha() function.
      //necessary because we need to pass the SVG image data to the response object of an HTTP server, which is used to send the image to the client's web browser
      const svg = svgCaptcha(answers.text, {
        size: 4,
        noise: 1,
        color: true,
        background: answers.shapeColor,
        width: 300,
        height: 200,
        fontSize: 80,
        charPreset: 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789',
        ignoreChars: '0o1i',
      }).data;
  
      // Set the text color
      const textColor = answers.textColor;
  
      // Add text to the SVG image
      const svgWithText = shape.addText(svg, answers.text, textColor);
  
      // Return the svg image to file
      return svgWithText;
  
    } catch (error) {
      console.error(error);
    }
  }
  
  module.exports = createLogo;